server:
  port: 8880

transport:
  netty:
    port: 19500
    bossThreads: 1
    workerThreads: 4

spring:
  application:
    name: IOT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/iot_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Gw@123456
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis-plus:
  repositoryPackage: info.zhihui.ems.**.repository
  mapperLocations: classpath*:mapper/**/*Repository.xml
  typeAliasesPackage: info.zhihui.ems.**.entity

logging:
  file:
    name: ./logs/iot.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    info.zhihui.ems: debug
  logback:
    rolling policy:
      max-file-size: 20MB
      max-history: 30
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [${PID}] [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [${PID}] [%thread] %-5level %logger{36} - %msg%n"